extends:
  - stylelint-config-rational-order
  - '../node_modules/prettier-stylelint/config.js'
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - extends
        - ignores
        - include
  indentation: 2
  string-quotes: single
