name: "orange"
version: "3.1"

services:
  db:
    image: postgres:15.2
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orange
