/* tslint:disable */
/* eslint-disable */
/**
 * Orange API
 * Orange API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {GetHello200Response} from '../models/index'
import {
  GetHello200ResponseFromJSON,
  GetHello200ResponseToJSON,
} from '../models/index'

export interface GetHelloRequest {
  name: string
}

/**
 *
 */
export class SampleApi extends runtime.BaseAPI {
  /**
   * Greet the user
   */
  async getHelloRaw(
    requestParameters: GetHelloRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetHello200Response>> {
    if (
      requestParameters.name === null ||
      requestParameters.name === undefined
    ) {
      throw new runtime.RequiredError(
        'name',
        'Required parameter requestParameters.name was null or undefined when calling getHello.'
      )
    }

    const queryParameters: any = {}

    if (requestParameters.name !== undefined) {
      queryParameters['name'] = requestParameters.name
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/hello`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetHello200ResponseFromJSON(jsonValue)
    )
  }

  /**
   * Greet the user
   */
  async getHello(
    requestParameters: GetHelloRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetHello200Response> {
    const response = await this.getHelloRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
