openapi: 3.0.0
info:
  title: Orange API
  description: Orange API
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /hello:
    get:
      operationId: getHello
      summary: Greet the user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  name:
                    type: string
      parameters:
        - name: name
          in: query
          description: The name of the person to greet
          required: true
          schema:
            type: string
      tags: ['sample']
